from __future__ import annotations

from pathlib import Path

LOCALIZATION_CHECKPOINT_NAME = "localization_dpn_unet_dpn92_0_best_dice"
DAMAGE_CHECKPOINT_NAME = "pseudo_dpn_seamese_unet_shared_dpn92_0_best_xview"

DEFAULT_LOCALIZATION_WEIGHTS_ENV = "LOCALIZATION_WEIGHTS_PATH"
DEFAULT_DAMAGE_WEIGHTS_ENV = "DAMAGE_WEIGHTS_PATH"
DEFAULT_MODEL_REPO_ENV = "HF_MODEL_REPO_ID"
DEFAULT_HF_REVISION_ENV = "HF_MODEL_REVISION"
DEFAULT_HF_TOKEN_ENV = "HF_TOKEN"

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LOCAL_DATA_DIR = PROJECT_ROOT / "data"
LOCAL_CACHE_DIR = LOCAL_DATA_DIR / "weights"

DEFAULT_NORMALIZE_MEAN = [0.485, 0.456, 0.406, 0.485, 0.456, 0.406]
DEFAULT_NORMALIZE_STD = [0.229, 0.224, 0.225, 0.229, 0.224, 0.225]

EPSG_4326 = "EPSG:4326"
